In [1]:
import pandas as pd

In [2]:
train = pd.read_csv("../Downloads/train hack.csv",header=None)
test = pd.read_csv("../Downloads/test hack.csv",header=None)

In [3]:
test

0                                                  1
0         Id                                             Review
1          1  \n Their best since "...And Justice For All" b...
2          2  \n Bob Dylan simply amazes me. He's one of the...
3          3  \n New York bands come, New York bands go, som...
4          4  \nIt may not hook and grab you immediately but...
5          5                  \n A stratospheric achievement.\n
6          6  \nThe album that passed Yeezus as my favourite...
7          7  \n Maybe I should give the band a higher numbe...
8          8  \nBlack Joe Lewis's Scandalous is a fun, raw, ...
9          9  \n Played it to death, rated it my favourite a...
10        10  \nThe Fame Monster is perfect from start to fi...
11        11  \nEvery time, I have to remind myself that thi...
12        12  \n A great introduction to Tropicalia and not ...
13        13  \nI'd heard some of these songs in more simple...
14        14  \nEasily the best album of the year, I found L...
15        15  \n This album is amazing. You have to listen t...
16        16  \n\n            This review contains spoilers,...
17        17  \n Gotta admit that when I first heard this al...
18        18  \n A much more subtle and evolved Hot Chip the...
19        19  \nI'd say that this will be the best rock albu...
20        20  \n If I could, I would give this album a 20. T...
21        21  \nExcellent record. These guys don't get half ...
22        22  \n This is the album Wilco should have made th...
23        23  \n This is the best stuff in a really long tim...
24        24  \n If not too modest to say, one of the best i...
25        25  \n I give it an 85% With the exception of a fe...
26        26  \n Simply a pop gem. It'll be a long while til...
27        27  \n Haunting lyrics with a brilliant mix of syn...
28        28            \n Just glorious. Absolutely love it.\n
29        29  \nBlack Sun is one of the top 5 releases since...
...      ...                                                ...
17621  17621  \nThe most urban album of Beyoncé's career. Th...
17622  17622  \nThis album is so under rated... Its a master...
17623  17623  \nLike before, Danny Brown has chosen to sound...
17624  17624  \n I know some might think an album like this ...
17625  17625  \n Not as great as his last album, but that's ...
17626  17626  \n this cd actually took me a while to get int...
17627  17627       \n Metal with a brain, and a soul as well.\n
17628  17628  \n One of the best discs of the year. Teddy ha...
17629  17629  \n listen to this now, because once it hits th...
17630  17630  \n A phenomenal hip-hop trip. Listening to thi...
17631  17631  \nHonestly, it’s been so long since I’ve heard...
17632  17632  \nIt seems like just yesterday that the four N...
17633  17633  \n This is a brilliant album wothy of ten out ...
17634  17634  \n actually worse than his last album!.....has...
17635  17635  \nTheir best album to date. A masterpiece. Ugh...
17636  17636  \nI've waited 15 years for this album. These g...
17637  17637  \n Beautifully dark and brooding. It has great...
17638  17638  \nLemonade é um álbum excelente, com vocais su...
17639  17639            \n A great album from a great artist.\n
17640  17640           \n bloc party the best band in britain\n
17641  17641  \nIs This It? is one of the masterpieces of co...
17642  17642  \n Minimalistic like Phillip Glass, but more m...
17643  17643  \n great album, with various elements. Krauss ...
17644  17644  \n Awesome CD - RT singing better than ever - ...
17645  17645  \nI love it, it has been almost a year but it ...
17646  17646  \n Actually, nothing about this album is overr...
17647  17647  \n Wild Mountain Nation may still be their bes...
17648  17648  \nThis is undoubtedly one of the most crisp an...
17649  17649  \n It's a difficult, but absolute amazing reco...
17650  17650           \n Out of this world...nothing like it\n

[17651 rows x 2 columns]

In [4]:
train = train.apply(lambda x: x.astype(str).str.lower())
test = test.apply(lambda x: x.astype(str).str.lower())

In [5]:
#print(train[1])

In [6]:
# converting pandas to numpy
x_train = train[1].values
y_train = train[2].values

x_test = test[1].values

x_test = x_test[1:]
x_train = x_train[1:]
y_train = y_train[1:]

print(len(x_train[3]))

128


In [7]:
print(x_test.shape)

(17650,)


In [8]:
import nltk

In [9]:
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from nltk.stem.snowball import PorterStemmer,SnowballStemmer
from nltk.stem.lancaster import LancasterStemmer
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer("[a-zA-Z0-9]+")
sw  = set(stopwords.words('english'))
ps = PorterStemmer()

In [10]:
import string
from string import punctuation

In [11]:
def getStemmedReview(review):
    
   

    review = review.replace("<br /><br />"," ")
    
    #Tokenize
    tokens = tokenizer.tokenize(review)
   
  
    
    new_tokens = [token for token in tokens if token not in sw]
    new_tokens = [token for token in new_tokens if  token.isalpha()]
    new_tokens = [token for token in new_tokens if len(token)>1]
   
    cleaned_review = ' '.join(new_tokens)

    
    return cleaned_review

In [12]:
l = len(x_train)
l1 = len(x_test)
print('\n')
for i in range(l):
    x_train[i] = getStemmedReview(x_train[i])
    
for i in range(l1):
    x_test[i] = getStemmedReview(x_test[i])
    
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
        
print(type(y_train))        



(35833,)
(17650,)
(35833,)
<class 'numpy.ndarray'>


In [13]:
x = pd.DataFrame(x_train)
y = pd.DataFrame(y_train)
for ix in range(x_train.shape[0]):
    review=x[0][ix]
    tokens = tokenizer.tokenize(review)
    x[0][ix]=tokens
    
print(x[0][4])

['things', 'like', 'streamlined', 'accessible', 'dont', 'mean', 'better', 'previous', 'albums', 'anything', 'means', 'disposable', 'doesnt', 'hold', 'severals', 'listens']


In [14]:
print(x[0][5])

['vince', 'gill', 'amazing', 'artist', 'magnificent', 'tenor', 'voice', 'songwriter', 'musician', 'anyone', 'seen', 'perform', 'live', 'go', 'away', 'thrilled']


In [15]:
xt = pd.DataFrame(x_test)
print(xt[0][16])

gotta admit first heard album thought ok years found returning repeated listens best played feeling mellow quiet introspective moments definitely party album songs much feeling help captured one alltime favorites hear gotta admit first heard album thought ok years found returning repeated listens best played feeling mellow quiet introspective moments definitely party album songs much feeling help captured one alltime favorites hear songs hard edge get live fillmore expand


In [16]:
xt = pd.DataFrame(x_test)

for ix in range(x_test.shape[0]):
    review=xt[0][ix]
    tokens = tokenizer.tokenize(review)
    xt[0][ix]=tokens
    


In [52]:
print(len(xt[0][4]))

25


In [18]:
print(y.shape)

(35833, 1)


In [20]:

import numpy as  np
np.unique(y_train)

array(['0.0', '1.0', '2.0', '3.0', '4.0'], dtype=object)

In [53]:
mean_len=30

In [54]:

def equal_len(x):
    for i in range(len(x[0])):
    #split_sen = x_train[i].split()
        if (len(x[0][i]) < mean_len):
            for j in range(abs(mean_len-len(x[0][i]))):
                x[0][i].append(0)
        if (len(x[0][i]) > mean_len):
            x[0][i] = x[0][i][0:mean_len] 
    return x
#dropout - reduce the length of sentence
            


In [55]:
print(x[0][9])

['solid', 'piece', 'work', 'features', 'lorde', 'best', 'self', 'melodramatic', 'raw', 'greenlight', 'writer', 'dark', 'personal', 'favorites', 'liabilities', 'loveless', 'trailing', 'behind', 'full', 'listen', 'appreciate', 'lorde', 'efforts', 'able', 'connect']


In [56]:
print(len(x[0][6]))

25


In [57]:
import gensim 
from gensim.models import word2vec
from gensim.models import KeyedVectors


In [58]:
word__vectors = KeyedVectors.load_word2vec_format('C:/Users/Amit/Downloads/GoogleNews-vectors-negative300.bin',binary=True)

In [59]:
v_apple = word__vectors["apple"]

In [60]:
print(v_apple.shape)

(300,)


In [61]:
#for ix in range(1,30):
#    print(len(x[0][ix]))

x = equal_len(x)
xt = equal_len(xt)

In [62]:
print(xt[0][98])

['gostei', 'muito', 'lbum', 'faz', 'muito', 'estilo', 'de', 'sica', 'que', 'beyonc', 'canta', 'tem', 'sicas', 'que', 'se', 'salvam', 'que', 'sorry', 'formation', 'inch', 'love', 'drought', 'essas', 'que', 'citei', 0, 0, 0, 0, 0]


In [63]:

def getOutputEmbeddings(X):
    
    embedding_out = np.zeros((X.shape[0],mean_len,300))
    count=0
    for ix in range(X.shape[0]):
        for jx in range(mean_len):
            try:
                 embedding_out[ix][jx] = word__vectors[X[0][ix][jx]]
                
            except:
                embedding_out[ix][jx] = np.zeros((300,))
            count+=1
            
    print(count)        
    return embedding_out
    

In [64]:
emb_xT = getOutputEmbeddings(x)
emb_xt = getOutputEmbeddings(xt)

1074990
529500


In [65]:
print(emb_xT.shape)

(35833, 30, 300)


In [66]:
from keras.utils import to_categorical

In [67]:
y_train = np.array([int(float(i)) for i in y_train])
print(y_train)

[0 3 2 ... 3 4 3]


In [68]:
#y= y_train.astype(int) 


In [69]:
m = to_categorical(y_train)

In [70]:
print(m)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


In [84]:
from keras.layers import *
from keras.models import Sequential


In [85]:
model = Sequential()
model.add(LSTM(64,input_shape=(mean_len,300),return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(64,input_shape=(mean_len,300)))
model.add(Dropout(0.2))
model.add(Dense(5))
model.add(Activation('softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_9 (LSTM)                (None, 30, 64)            93440     
_________________________________________________________________
dropout_9 (Dropout)          (None, 30, 64)            0         
_________________________________________________________________
lstm_10 (LSTM)               (None, 64)                33024     
_________________________________________________________________
dropout_10 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 325       
_________________________________________________________________
activation_5 (Activation)    (None, 5)                 0         
Total params: 126,789
Trainable params: 126,789
Non-trainable params: 0
_________________________________________________________________


In [86]:
from keras.callbacks import EarlyStopping

earlystop = EarlyStopping(monitor='val_acc',patience=3)


model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
model.fit(emb_xT,m,batch_size=32,epochs=20,shuffle=True,validation_split=0.1)

Train on 32249 samples, validate on 3584 samples
Epoch 1/20
32249/32249 [==============================] - 77s 2ms/step - loss: 1.0385 - acc: 0.5587 - val_loss: 0.9288 - val_acc: 0.6018
Epoch 2/20
32249/32249 [==============================] - 74s 2ms/step - loss: 0.9466 - acc: 0.5967 - val_loss: 0.9356 - val_acc: 0.6122
Epoch 3/20
32249/32249 [==============================] - 76s 2ms/step - loss: 0.9228 - acc: 0.6033 - val_loss: 0.9050 - val_acc: 0.6180
Epoch 4/20
32249/32249 [==============================] - 74s 2ms/step - loss: 0.9015 - acc: 0.6143 - val_loss: 0.8982 - val_acc: 0.6222
Epoch 5/20
32249/32249 [==============================] - 73s 2ms/step - loss: 0.8803 - acc: 0.6228 - val_loss: 0.9091 - val_acc: 0.6256
Epoch 6/20
32249/32249 [==============================] - 77s 2ms/step - loss: 0.8611 - acc: 0.6321 - val_loss: 0.8870 - val_acc: 0.6278
Epoch 7/20
32249/32249 [==============================] - 75s 2ms/step - loss: 0.8358 - acc: 0.6403 - val_loss: 0.8959 - val_acc:

In [87]:
print(xt[0][91])

['better', 'vulnicura', 'success', 'optimistic', 'traumas', 'typical', 'singleness', 'escape', 'electronic', 'spring', 'femininity', 'telephatic', 'journey', 'hidden', 'place', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [88]:
pred = model.predict_classes(emb_xt)

In [89]:
print(pred)


[4 4 3 ... 4 4 4]


In [90]:
pred = pd.DataFrame(pred)
print(type(pred))

<class 'pandas.core.frame.DataFrame'>


In [91]:
#for ix in range(len(pred)):
#    if pred[0][ix]==1:
#        pred[0][ix]='pos'
#    else:
#        pred[0][ix]='neg'



In [92]:
print(pred)

       0
0      4
1      4
2      3
3      3
4      4
5      2
6      2
7      3
8      4
9      4
10     4
11     3
12     4
13     4
14     4
15     4
16     4
17     3
18     2
19     3
20     3
21     4
22     3
23     4
24     4
25     3
26     4
27     4
28     3
29     4
...   ..
17620  4
17621  4
17622  3
17623  2
17624  4
17625  3
17626  4
17627  4
17628  3
17629  3
17630  3
17631  2
17632  4
17633  1
17634  4
17635  4
17636  4
17637  4
17638  4
17639  4
17640  4
17641  4
17642  4
17643  3
17644  4
17645  2
17646  4
17647  4
17648  4
17649  4

[17650 rows x 1 columns]


In [93]:
export_csv = pred.to_csv (r"C:/Users/Amit/Documents/output/music_ans9.csv", header='label') #Don't forget to add '.csv' at the end of the path


In [ ]:
#print(pred)